### ISSUE TITLE
如果要打包多页面的话如何修改webpack呢

### ISSUE THREAD

**Issue by MorisHarA** [SidKwok/react-webpack-boilerplate#11]

**Comment by SidKwok** [comment]
多页面情的话和spa不同的地方很多，会考虑另外写一个模版

**Comment by MorisHarA** [comment]
有空搞一个多页的模板出来么？？

**Comment by SidKwok** [comment]
This template is for single page application. May consider create a new template for multiple pages application.

**Comment by lcxlw2d** [comment]
还是想问一下多页应用要怎么改，用这套开发有几周了，现在换模板有点尴尬
