### ISSUE TITLE
请问要怎么开启sass的modules

### ISSUE THREAD

**Issue by RongleCat** [SidKwok/react-webpack-boilerplate#12]
请问要怎么开启sass的modules

**Comment by SidKwok** [comment]
使用sass要安装sass-loader和node-sass
```bash
npm install --save-dev sass-loader node-sass
```
[相关说明](https://github.com/SidKwok/react-webpack-boilerplate/blob/master/zh-README.md#pre-processor)

**Comment by RongleCat** [comment]
我在utils.js中修改了
const cssLoader = {
        loader: 'css-loader',
        options: {
            minimize: process.env.NODE_ENV === 'production',
            sourceMap: options.sourceMap,
            modules:'&localIdentName=[hash:base64:5]&-url'
        }
    };
成功开启了

**Comment by SidKwok** [comment]
如果是css modules的话就是这样修改就可以了
