### ISSUE TITLE
使用webpack结合路由按需加载

### ISSUE THREAD

**Issue by MorisHarA** [SidKwok/react-webpack-boilerplate#13]
为什么chunk把有的第三方库也打包进去了？但是有的又被打包到vendor里面？

**Comment by SidKwok** [comment]
能贴一下相关代码吗？

**Comment by MorisHarA** [comment]
export default [
  {
    path:'/',
    onEnter: (nextState, replace) => replace('/homepage')
  },
  {
    path:'/homepage',
    getComponents(nextState, cb) {
      require.ensure([], (require)=>{
        cb(null, require('components/homepage').default)
      },'homepage')
    },
    onEnter: (nextState,replace) =>{
      recoverPosition('homepage')
    },
    onLeave: (preState) =>{
      const scrollTop = document.body.scrollTop;
      savePosition('homepage',scrollTop)
    }
  },
  {
    path:'/detail',
    getComponents(nextState, cb) {
      require.ensure([], (require)=> {
        cb(null, require('components/detail').default)
      },'detail')
    }
  },
  {
    path: '/comment',
    getComponents(nextState, cb) {
      require.ensure([], (require)=> {
        cb(null, require('components/comment').default)
      },'comment')
    }
  }
]

**Comment by MorisHarA** [comment]
...部分路由 我图片贴不上去，我直接发你邮箱

**Comment by MorisHarA** [comment]
发过去了

**Comment by SidKwok** [comment]
react-router的版本是什么？

**Comment by MorisHarA** [comment]
v3

**Comment by MorisHarA** [comment]
正常打包出来的是应该每个路由页面都不含node_modules的东西吗？

**Comment by SidKwok** [comment]
正常打包的话应该最上层会有一个node_modules包着的，你code split的拆分点有几个？就只有路由那里进行了拆分吗？

**Comment by MorisHarA** [comment]
你脚手架生成的配置我都没动，就是路由做了code split ，需要配置什么东西吗？

**Comment by SidKwok** [comment]
正常来说不需要的，但是我不清楚你路由里面是怎么引用依赖的，方便把工程打包发过来让我看看吗？

**Comment by MorisHarA** [comment]
好的  我发给你

**Comment by SidKwok** [comment]
我好像有一点头绪了。

你引入了antd-mobile这个库，然后在各个路由引入了各种组件对吧？如果你这样子进行code-split的话很有可能将一些依赖(例如lodash）重复打包了。

例如你有两个进行分割的路由a和b，a和b都用了lodash，那么分割的时候lodash会被重复打包到a和b中（为了确保每一个路由都能正常运行，避免这种情况的一个方法是在a和b的上层路由直接引入lodash。

你试一试这种方法是否可以避免这个问题。

（重复打包了的依赖你在App.jsx里面引入试一下）

**Comment by MorisHarA** [comment]
我试下

**Comment by MorisHarA** [comment]
------------------ 原始邮件 ------------------
发件人: "Sid";<notifications@github.com>;
发送时间: 2017年4月18日(星期二) 下午3:32
收件人: "SidKwok/react-webpack-boilerplate"<react-webpack-boilerplate@noreply.github.com>; 
抄送: "栾大鹏"<1245686914@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [SidKwok/react-webpack-boilerplate] 使用webpack结合路由按需加载 (#13)




我好像有一点头绪了。
 
你引入了antd-mobile这个库，然后在各个路由引入了各种组件对吧？如果你这样子进行code-split的话很有可能将一些依赖(例如lodash）重复打包了。
 
例如你有两个进行分割的路由a和b，a和b都用了lodash，那么分割的时候lodash会被重复打包到a和b中（为了确保每一个路由都能正常运行，避免这种情况的一个方法是在a和b的上层路由直接引入lodash。
 
你试一试这种方法是否可以避免这个问题。
 
（重复打包了的依赖你在App.jsx里面引入试一下）

**Comment by MorisHarA** [comment]
我还是发给你看看吧  我的lodash是配置在webpack ProvidePlugin里面的，按道理不应该重复打包进去啊

**Comment by MorisHarA** [comment]
发过去了

**Comment by SidKwok** [comment]
webpack ProvidePlugin不能起到相关作用的，因为这个插件只是说当你在用lodash的时候它自动帮你import，所以跟你在组件里面import是一样的。在根组件`import _ from 'lodash'`应该能解决这个问题

**Comment by MorisHarA** [comment]
那为啥 axios 被打包到vendor里面去了 并且没有被打到每个路由页面  我也是在 ProvidePlugin里面配置的。。

**Comment by MorisHarA** [comment]
懂了  因为我有个axios配置文件 被引到main.js了  相当于全局导入了。。
