### ISSUE TITLE
后端要以这样的链接访问应用  xxxxx.com/ActivityWeb/  那路由不匹配了

### ISSUE THREAD

**Issue by MorisHarA** [SidKwok/react-webpack-boilerplate#16]
需要改什么配置吗？

**Comment by SidKwok** [comment]
SPA的后端配置你可以google一下，具体思路是将前端看作静态资源，nginx的配置会相对简单一点点。

**Comment by MorisHarA** [comment]
react路由好像没vue路由的base这个功能。。。那我每个路由前面的公共路由是要手动每个加上去吗。。

**Comment by SidKwok** [comment]
这个你可以设置最高嵌套的那个路由啊，具体配置看一下文档
