### ISSUE TITLE
脚手架生成的项目不支持ios8，页面打不开

### ISSUE THREAD

**Issue by MorisHarA** [SidKwok/react-webpack-boilerplate#18]
ios9 ios10 都能运行，并且之前上个月使用的版本的脚手架可以在ios8运行，现在不行了

**Comment by SidKwok** [comment]
暂时还没有设备去调试这个，我先看看之前的commit

**Comment by MorisHarA** [comment]
你看我的issue，最早的那次在一个月前，那时候的版本还没有集成单元测试好像

**Comment by MorisHarA** [comment]
本地ios8可以跑的，打包完就挂了，就算页面什么都没有react.render一个hello都挂

**Comment by MorisHarA** [comment]
"production": {
      "presets": ["react-optimize"]
   }  找到原因了 babel加了这个配置ios8以下就不工作了

**Comment by SidKwok** [comment]
但是模版里面本来就有这个配置的啊

**Comment by MorisHarA** [comment]
对啊，所以模版刚生成的项目也不能在ios8以下运行，我之前上上个项目用你的模板babel里面是没这个的，所以可以运行

**Comment by MorisHarA** [comment]
你可以下个xcode 模拟器来模拟，然后再安装ios8，可以让bug重现

**Comment by SidKwok** [comment]
@MorisHarA 这个是插件的问题 但是作者已经关闭issue了。。所以我直接移除这个插件了。
