### ISSUE TITLE
Warning: [react-router] You cannot change <Router routes>; it will be ignored

### ISSUE THREAD

**Issue by chenz24** [SidKwok/react-webpack-boilerplate#2]
RT, 热加载会报错

BTW，很好的boilerplate

**Comment by SidKwok** [comment]
结合了Router v3会出现这个问题。目前正在修复。
谢谢支持

**Comment by chenz24** [comment]
发现一个hack的方法，就是给router加随机数
`<Router history={history} routes={routes} key={Math.random()}/>`
这样可以暂时用着

**Comment by SidKwok** [comment]
已采用作为暂时的解决方案。

v4好像没有这个问题
