### ISSUE TITLE
dalao  请问你为什么要给router加一个key?

### ISSUE THREAD

**Issue by Jemair** [SidKwok/react-webpack-boilerplate#29]
```JS
export default class App extends Component {
  render() {
    return (
      <div className={styles.App}>
        <Router history={history} routes={routes} key={Math.random()} />
      </div>
    )
  }
}
```

**Comment by SidKwok** [comment]
这是react-router v3已知的一个bug，不加key属性会导致热更新的时候出错

**Comment by Jemair** [comment]
可是加了以后会有问题啊。。。
我查了一晚上啊/捂脸

**Comment by SidKwok** [comment]
噢？什么问题

**Comment by Jemair** [comment]
react会以为加载前后是两个组件
所以会调两次mount...

一般不会有什么问题 
可是我在mount里打点   所以一个页面会统计两次   至今不敢告诉领导昨天业绩特别好是因为我打点打错了 23333

**Comment by SidKwok** [comment]
其实可以考虑在生产环境下用不加key的路由

**Comment by Jemair** [comment]
我不太清楚具体原因   
我在componentDidMount里调用方法修改了store就会出现这个问题
如果不修改store就不会出现问题
我现在很明确就是这个key导致的问题
下班了。。。。。

**Comment by SidKwok** [comment]
脚手架提供了一个环境变量，你可以通过这个来切换你的生产环境代码

**Comment by Jemair** [comment]
嗯嗯。。。
谢谢dalao半夜还回我issue   可以close了
