### ISSUE TITLE
Async Component won't hot reload

### ISSUE THREAD

**Issue by SidKwok** [SidKwok/react-webpack-boilerplate#34]

**Comment by ChiaJune** [comment]
这个我之前遇到过，好像是`react-hot-loader`版本的问题，升级到正式版v3.0.0以后，编辑器改动代码，浏览器`console`报一大堆错。但是我把版本控制到`v3.0.0-beta7`好像没啥问题

**Comment by SidKwok** [comment]
我把版本控制到了 `v3.0.0-beta7` 也不行啊，就是 Async Component 没有办法热加载。提个PR我看看？

**Comment by ChiaJune** [comment]
实在抱歉，我重新用`sao`构建了一个项目，更改了`react-hot-loader`版本，发现也不好使，我也不知道什么原因。我现在开发的项目，是在原来的基础上改动过的，没有使用`react-router-config`，而是使用的`react-router-redux`，我想应该不是因为使用其中的一个造成的。等有空再试一试

**Comment by SidKwok** [comment]
谢谢帮忙
