### ISSUE TITLE
给CSS属性加上前缀

### ISSUE THREAD

**Issue by isClumsyBird** [SidKwok/react-webpack-boilerplate#6]
### 如题

`num run dev` 开发模式下 或 `npm run build`打包过后，CSS属性并没有自动加上前缀，请问这个该如何配置？

**Comment by SidKwok** [comment]
这个bug在前几天修复了，默认加入了postcss的支持。

你重新安装一下模版试试？
```bash
sao SidKwok/react-webpack-boilerplate yourproject --install
```

**Comment by isClumsyBird** [comment]
重新`npm install -g sao`再生成项目就好了。感谢感谢！
