### ISSUE TITLE
关于ESLint和下载模板的建议

### ISSUE THREAD

**Issue by isClumsyBird** [SidKwok/react-webpack-boilerplate#8]
现在这个React模板的ESLint使用的是standard来检测代码风格。
我的建议是，请作者加上其他类型代码风格检测的选择，就像vue-cli那样(可以选择多个)：
- Standard
- Airbnb
- none(configure it yourself)

不知道作者是否有这方面的打算？

--- 

还有就是下载模板这一步：
``` bash
# 下载模版
sao SidKwok/react-webpack-boilerplate new-project --install
```
感觉命令好长，能简练一点就好了:blush:

**Comment by SidKwok** [comment]
因为airbnb和standard处理jsx-quotes的不同（airbnb是双引号，standard是单引号），这样子会导致模版文件比较难处理。不过应该可以通过一些hack的手段来处理（例如使用css module来避免className带来引号问题），这里我再想想。
至于名字的长短，我考虑一下把项目名字弄短吧😂，谢谢意见。

**Comment by isClumsyBird** [comment]
感谢回复!:thumbsup:
