### ISSUE TITLE
Cannot read property 'apply' of undefined 

### ISSUE THREAD

**Issue by MorisHarA** [SidKwok/react-webpack-boilerplate#9]
npm run dev 出现错误

**Comment by SidKwok** [comment]
能给出重现过程吗

**Comment by MorisHarA** [comment]
照着命令行从头走一遍就有了

**Comment by SidKwok** [comment]
请提供一下node版本

**Comment by MorisHarA** [comment]
v6.10.0

**Comment by SidKwok** [comment]
所有特性都使用了吗？redux，router那些都选了吗？

**Comment by MorisHarA** [comment]
都选了，系统是mac

**Comment by SidKwok** [comment]
@MorisHarA 我这边重现不了你的bug呢，要不要试下重新安装一下模版

**Comment by MorisHarA** [comment]
重新安装了，还是不行，你邮箱什么，我发你截图吧

**Comment by SidKwok** [comment]
oceankwok@hotmail.com, 你也可以直接把截图拉拽到评论框的

**Comment by SidKwok** [comment]
收到你的邮件了，但是不知道为什么发不到邮件给你，所以在这里回复你。
你可以把你生成的文件直接压缩成zip包发给我吗？这样子我好排查问题

**Comment by MorisHarA** [comment]
我把node_modules也打包过去了,我试了下test是可以的 build后起静态文件服务器是也可以跑起来，唯一不可以的就是dev跑不起来

**Comment by SidKwok** [comment]
@MorisHarA 没看到你发的邮件呢

**Comment by MorisHarA** [comment]
还没收到吗？？

**Comment by SidKwok** [comment]
对啊 没有收到

**Comment by MorisHarA** [comment]
我发了好几遍了啊。。。

**Comment by charlzyx** [comment]
windows 10, node: 7.4 基本上一路next, router: v4, cnpm 安装

![1](https://cloud.githubusercontent.com/assets/18055018/24509709/a96986d8-1599-11e7-9435-ae31e35a5dc2.png)
![2](https://cloud.githubusercontent.com/assets/18055018/24509715/adca138c-1599-11e7-98a1-a3a3e5231654.png)
![3](https://cloud.githubusercontent.com/assets/18055018/24509721/aff42f08-1599-11e7-934f-b0091b6a21f3.png)

**Comment by SidKwok** [comment]
@MorisHarA @charlzyx 这是因为你们选择了browser devtools而没有安装相应的chrome插件。但是现在我做了个优化，用devtools自带的compose作为enhancer，问题应该已经解决了，你们重新安装模版试一下：
```bash
sao SidKwok/react-webpack-boilerplate new-project --install
```

**Comment by MorisHarA** [comment]
昨晚关灯了了，收到邮件爬起来试了试，可以的
